# Generated by Django 5.1.5 on 2025-02-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=35)),
                ('receiver', models.CharField(max_length=35)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XRPLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=35, unique=True)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('secret', models.CharField(max_length=35)),
            ],
        ),
    ]
