# Generated by Django 5.1.5 on 2025-02-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XrplAccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=20)),
                ('flags', models.IntegerField()),
                ('ledger_entry_type', models.CharField(max_length=100)),
                ('owner_count', models.IntegerField()),
                ('previous_txn_id', models.CharField(max_length=255)),
                ('previous_txn_lgr_seq', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('index', models.CharField(max_length=255)),
                ('allow_trustline_clawback', models.BooleanField(default=False)),
                ('default_ripple', models.BooleanField(default=False)),
                ('deposit_auth', models.BooleanField(default=False)),
                ('disable_master_key', models.BooleanField(default=False)),
                ('disallow_incoming_check', models.BooleanField(default=False)),
                ('global_freeze', models.BooleanField(default=False)),
                ('no_freeze', models.BooleanField(default=False)),
                ('password_spent', models.BooleanField(default=False)),
                ('require_authorization', models.BooleanField(default=False)),
                ('require_destination_tag', models.BooleanField(default=False)),
                ('ledger_hash', models.CharField(max_length=255)),
                ('ledger_index', models.IntegerField()),
                ('validated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'xrpl_account_data',
            },
        ),
        migrations.CreateModel(
            name='XrplLedgerEntryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_index', models.CharField(max_length=64, unique=True)),
                ('close_time_iso', models.DateTimeField()),
                ('ctid', models.CharField(max_length=16)),
                ('hash', models.CharField(max_length=64)),
                ('seq', models.IntegerField()),
                ('ticket_count', models.IntegerField()),
                ('ledger_entry_type', models.CharField(max_length=32)),
                ('previous_fields_balance', models.BigIntegerField()),
                ('previous_txn_id', models.CharField(max_length=64)),
                ('previous_txn_lgr_seq', models.IntegerField()),
                ('account', models.CharField(max_length=64)),
                ('balance', models.BigIntegerField()),
                ('flags', models.IntegerField()),
                ('owner_count', models.IntegerField()),
                ('transaction_index', models.IntegerField()),
                ('transaction_result', models.CharField(max_length=16)),
                ('delivered_amount', models.BigIntegerField()),
                ('validated', models.BooleanField()),
            ],
            options={
                'db_table': 'xrpl_ledger_entry_data',
            },
        ),
        migrations.CreateModel(
            name='XrplPaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=35)),
                ('receiver', models.CharField(max_length=35)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xrpl_payment_data',
            },
        ),
        migrations.CreateModel(
            name='XrplTransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64)),
                ('deliver_max', models.BigIntegerField()),
                ('destination', models.CharField(max_length=64)),
                ('fee', models.BigIntegerField()),
                ('flags', models.IntegerField()),
                ('last_ledger_sequence', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('signing_pub_key', models.CharField(max_length=128)),
                ('transaction_type', models.CharField(max_length=16)),
                ('txn_signature', models.TextField()),
                ('date', models.DateTimeField()),
                ('ledger_index', models.IntegerField()),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='xrpl_api.xrplledgerentrydata')),
            ],
            options={
                'db_table': 'xrpl_transaction_data',
            },
        ),
    ]
