# Generated by Django 5.1.6 on 2025-03-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrpl_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowtransaction',
            name='condition',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='fulfillment',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='escrowtransactionaffectednode',
            name='condition',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
