# Generated by Django 5.1.6 on 2025-02-13 05:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrpl_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='xrplaccountdata',
            managers=[
                ('xrpl_account_data_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='xrplledgerentrydata',
            managers=[
                ('xrpl_ledger_entry_data_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='xrplpaymentdata',
            managers=[
                ('xrpl_payment_data_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='xrpltransactiondata',
            managers=[
                ('xrpl_transaction_data_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
