# Generated by Django 5.1.6 on 2025-02-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrpl_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lastclose',
            table='xrpl_server_last_close',
        ),
        migrations.AlterModelTable(
            name='port',
            table='xrpl_server_port',
        ),
        migrations.AlterModelTable(
            name='stateaccountingentry',
            table='xrpl_server_state_accounting_entry',
        ),
        migrations.AlterModelTable(
            name='validatedledger',
            table='xrpl_server_validated_ledger',
        ),
    ]
