# Generated by Django 5.1.6 on 2025-02-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrpl_api', '0002_alter_xrplaccountdata_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='xrplaccountdata',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='xrplledgerentrydata',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='xrplpaymentdata',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='xrpltransactiondata',
            managers=[
            ],
        ),
    ]
