# Generated by Django 5.1.6 on 2025-02-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrpl_api', '0003_alter_xrplaccountdata_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrplaccountdata',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
