# Generated by Django 5.1.6 on 2025-02-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrpl_api', '0004_alter_xrplaccountdata_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrplpaymentdata',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
